### PR TITLE
Api 4444/update contact form

### PR DESCRIPTION
**Pull request by RockslideJr**
This updates the contact form handler to handle the new values that will be introduced to the contact form (see [API-4444](https://vajira.max.gov/browse/API-4444) ) Once the front end updates have been made, another PR will be made to update the Joi types to be stricter in regards to the form fields relationship.

### CODE REVIEW

**Review by maddy-jo — COMMENTED** [review]
did a pretty quick review, and my one big question is around the design decision for having one ContactUs route handler for providers and consumers or splitting out separate ones for each use case. could go either way but would love to hear your thoughts on that question. beyond that question, I think everything looks pretty good as far as I can see!

**Review by alexandervalencia — COMMENTED** [review]
Just a few typos, and we should look into setting up `prettier` for this repo. Other than that looks good!

**Review by rtravitz — DISMISSED** [review]
Happy with it in general. Up to you about how you want to handle the outstanding comments. Nice work ✨

**Review by TS000 — DISMISSED** [review]
Looked over the comments and things are looking great! Nice job tackling this!

**Review by rtravitz — APPROVED** [review]

**Pull request merged**
