### PR TITLE
Api 2367/handle silent slack errors

### PR DESCRIPTION
**Pull request by nwalker-va**
This PR is for [API-2367](https://vajira.max.gov/secure/RapidBoard.jspa?rapidView=465&view=detail&selectedIssue=API-2367). It throws an error when the Slack API returns an error (returns with a 200 status, but an ok: false). I also added a test.

### CODE REVIEW

**Review by michaelkimball — COMMENTED** [review]
Can we add a test to check for the absence of the charset warning just to prevent regression in the future? Otherwise I like it

**Review by maddy-jo — DISMISSED** [review]
looks great!! ✨ 🚀

**Review by rtravitz — COMMENTED** [review]
Nice job @nwalker-va. Agree about enforcing the charset with an assertion if that's important going forward.

**Review by maddy-jo — DISMISSED** [review]
💅 ✨ 🚀

**Review by anthony-kopczyk — COMMENTED** [review]
Looks good. Do have a question on the error handling. If we should log warnings, and also if we should check `res.data.ok` in addition to if there are errors, in some crazy scenario that it's no ok but doesn't have errors listed, if that's even possible with the slack API.

**Review by michaelkimball — APPROVED** [review]
There is a comment about warnings from @anthony-kopczyk  that has some merit, but up to you if you want to do it @nwalker-va. Looks good to me otherwise

**Pull request merged**
