### PR TITLE
API-5279: Update dependencies

### PR DESCRIPTION
**Pull request by anthony-kopczyk**
Updated all of the backend packages to the latest and ran `npm audit fix`

Jira Ticket: https://vajira.max.gov/browse/API-5279

### CODE REVIEW

**Review by johanna-adhoc — CHANGES_REQUESTED** [review]
Can you run the commands npm audit and npm audit fix as part of this ticket?

**Review by johanna-adhoc — DISMISSED** [review]
LGTM. Eslint updates will be handled with ticket https://vajira.max.gov/browse/API-5355

**Review by johanna-adhoc — DISMISSED** [review]

**Review by johanna-adhoc — APPROVED** [review]
LGTM

**Review by TS000 — APPROVED** [review]
LGTM!

**Pull request merged**
